# Generated by Django 4.1 on 2023-05-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookuser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookuser",
            name="create_time",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="bookuser",
            name="cusAccount",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="bookuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="bookuser",
            name="reserve1",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="bookuser",
            name="status",
            field=models.CharField(max_length=255),
        ),
    ]
